### PR TITLE
MAC Discover Authentication + Device Name Consistency + Discover Documentation

### LINKED ISSUE #22: Startup delay/blocking when missing credentials
On startup, the service attempts to create a device client for each registered device. This causes it to lookup the camera credentials secrets. When the secrets do not exist, it waits up to 2 minutes for them, for each device. This all happens serially and delays the starting of the service.

```
level=INFO ts=2022-03-29T00:39:55.184382784Z app=device-onvif-camera source=driver.go:86 msg="Initializing device client for '3fa1fe68-b915-4053-a3e1-1027f5ea88f4' camera"
level=WARN ts=2022-03-29T00:39:55.184402418Z app=device-onvif-camera source=driver.go:283 msg="Unable to retrieve camera credentials from SecretProvider at path '3fa1fe68-b915-4053-a3e1-1027f5ea88f4': Error, path (3fa1fe68-b915-4053-a3e1-1027f5ea88f4) doesn't exist in secret store. Retrying for 1m59.999998509s"
level=WARN ts=2022-03-29T00:39:56.184607352Z app=device-onvif-camera source=driver.go:283 msg="Unable to retrieve camera credentials from SecretProvider at path '3fa1fe68-b915-4053-a3e1-1027f5ea88f4': Error, path (3fa1fe68-b915-4053-a3e1-1027f5ea88f4) doesn't exist in secret store. Retrying for 1m58.999817495s"
...
level=ERROR ts=2022-03-29T00:41:55.234543205Z app=device-onvif-camera source=driver.go:90 msg="failed to initial device client for '3fa1fe68-b915-4053-a3e1-1027f5ea88f4' camera, skipping this device."
```

https://github.com/edgexfoundry-holding/device-onvif-camera/blob/27426708967fb713f3ef9396d946112ad1b0b7a6/internal/driver/driver.go#L80-L91

### LINKED ISSUE #83: Get credentials retry loop ignores SIGINT
The GetCredentials rety loop is not hooked up with any other signaling to cancel when a `SIGINT` or other is sent to the process. This will delay shutdown as either the timer has to run out or the user has to `SIGKILL` the process.

## 🔥 Exception or Error
<pre><code>
level=WARN ts=2022-06-16T21:38:54.879604779Z app=device-onvif-camera source=credentials.go:61 msg="Unable to retrieve camera credentials from SecretProvider at path '3fa1fe68-b915-4053-a3e1-1027f5ea88f4': Error, path (3fa1fe68-b915-4053-a3e1-1027f5ea88f4) doesn't exist in secret store. Retrying for 1m32.987007063s"
level=WARN ts=2022-06-16T21:38:55.879965419Z app=device-onvif-camera source=credentials.go:61 msg="Unable to retrieve camera credentials from SecretProvider at path '3fa1fe68-b915-4053-a3e1-1027f5ea88f4': Error, path (3fa1fe68-b915-4053-a3e1-1027f5ea88f4) doesn't exist in secret store. Retrying for 1m31.986646081s"
level=WARN ts=2022-06-16T21:38:56.880378244Z app=device-onvif-camera source=credentials.go:61 msg="Unable to retrieve camera credentials from SecretProvider at path '3fa1fe68-b915-4053-a3e1-1027f5ea88f4': Error, path (3fa1fe68-b915-4053-a3e1-1027f5ea88f4) doesn't exist in secret store. Retrying for 1m30.986235633s"
^C
level=INFO ts=2022-06-16T21:38:57.799049308Z app=device-onvif-camera source=config.go:318 msg="Watching for 'AppCustom' configuration changes has stopped"
level=INFO ts=2022-06-16T21:38:57.799666781Z app=device-onvif-camera source=messaging.go:88 msg="Disconnected from MessageBus"
level=INFO ts=2022-06-16T21:38:57.799047447Z app=device-onvif-camera source=config.go:467 msg="Watching for '/Writable' configuration changes has stopped"
level=INFO ts=2022-06-16T21:38:57.799768165Z app=device-onvif-camera source=httpserver.go:126 msg="Web server shutting down"
level=ERROR ts=2022-06-16T21:38:57.799842391Z app=device-onvif-camera source=httpserver.go:143 msg="Web server failed: http: Server closed"
level=INFO ts=2022-06-16T21:38:57.801041628Z app=device-onvif-camera source=httpserver.go:128 msg="Web server shut down"
level=WARN ts=2022-06-16T21:38:57.881311693Z app=device-onvif-camera source=credentials.go:61 msg="Unable to retrieve camera credentials from SecretProvider at path '3fa1fe68-b915-4053-a3e1-1027f5ea88f4': Error, path (3fa1fe68-b915-4053-a3e1-1027f5ea88f4) doesn't exist in secret store. Retrying for 1m29.985302169s"
level=WARN ts=2022-06-16T21:38:58.882085199Z app=device-onvif-camera source=credentials.go:61 msg="Unable to retrieve camera credentials from SecretProvider at path '3fa1fe68-b915-4053-a3e1-1027f5ea88f4': Error, path (3fa1fe68-b915-4053-a3e1-1027f5ea88f4) doesn't exist in secret store. Retrying for 1m28.984519117s"
level=WARN ts=2022-06-16T21:38:59.882383818Z app=device-onvif-camera source=credentials.go:61 msg="Unable to retrieve camera credentials from SecretProvider at path '3fa1fe68-b915-4053-a3e1-1027f5ea88f4': Error, path (3fa1fe68-b915-4053-a3e1-1027f5ea88f4) doesn't exist in secret store. Retrying for 1m27.984228452s"

</code></pre>

**Anything else relevant?**

Should probably use similar code to the `taskLoop`

### LINKED ISSUE #86: HTTP 503 error responses from core command
This seems to happen when the device service is stuck in a getCredentials retry loop. Even devices which DO have proper authentication are getting 503 errors when being called by the command service. I assume this is due to some sort of blocking or botteneck occurring in the sdk from the getCredentials loop.

image

### PR DESCRIPTION
**Pull request by ajcasagrande**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-examples/blob/master/.github/CONTRIBUTING.md.

## Issue Number:
Closes #86 
Closes #83 
Closes #22

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## New Imports
Are there any new imports or modules? If so, what are they used for and why?

## Specific Instructions
Are there any specific instructions or things that should be known prior to reviewing?

## Other information

### CODE REVIEW

File: bin/configure-subnets.sh [hunk 1]
```diff
@@ -0,0 +1,50 @@
+#!/usr/bin/env bash
+
+#
+# Copyright (C) 2020-2022 Intel Corporation
```
Comment (presatish) [inline bin/configure-subnets.sh]: `2020 `can be removed.

**Review by presatish — DISMISSED** [review]
Overall LGTM, one small change needed.

File: doc/auto-discovery.md [hunk 2]
```diff
@@ -1,297 +1,192 @@
...
+### Add Credentials to Unknown Camera
 If a camera is discovered in which the credentials are unknown, it will be
 added as a generic onvif camera, and will require the user to set the credentials
 in order to call most ONVIF commands.
 
+Credentials can be added and modified via [utility scripts](./utility-scripts.md#use-cases)
+
 #### Non-Secure Mode
 ##### Helper Script
 Run the [bin/set-credentials.sh](../bin/set-credentials.sh) script
```
Comment (ChristianDarr-personal) [inline doc/auto-discovery.md]: map-credentials.sh

File: doc/auto-discovery.md [hunk 3]
```diff
@@ -1,297 +1,192 @@
...
+
+#### both
+This option combines both [netscan](#netscan) and [multicast](#multicast).
+
+### DiscoverySubnets
+> For docker, set the env var `APPCUSTOM_DISCOVERYSUBNETS`
+
+This is the list of IPv4 subnets to perform netscan discovery on, in CIDR format (X.X.X.X/Y)
+separated by commas ex: "192.168.1.0/24,10.0.0.0/24". This value can be configured automatically via
+the [bin/configure-subnets.sh](../bin/configure-subnets.sh) script.
```
Comment (ChristianDarr-personal) [inline doc/auto-discovery.md]: I would link to the utility scripts doc

File: doc/auto-discovery.md [hunk 4]
```diff
@@ -1,297 +1,192 @@
...
+#### multicast
+`multicast` works by sending a single multicast UDP [WS-Discovery](./ws-discovery.md) Probe to the multicast address `239.255.255.250` on port `3702`.
+In certain networks this traffic is blocked, and it is also not forwarded across subnets, so it is not compatible with NATs
+such as docker networks (except in the case of running an Onvif simulator inside the same docker network).
+
+#### both
+This option combines both [netscan](#netscan) and [multicast](#multicast).
+
+### DiscoverySubnets
+> For docker, set the env var `APPCUSTOM_DISCOVERYSUBNETS`
```
Comment (ChristianDarr-personal) [inline doc/auto-discovery.md:139]: For all of these, it might be good to show an example value. So APPCUSTOM_DISCOVERYETHERNETINTERFACE=eth0 or something like that

**Review by ChristianDarr-personal — COMMENTED** [review]
LGTM

File: doc/auto-discovery.md (hunk 4 above)
Comment (ajcasagrande) [reply doc/auto-discovery.md:139]: Will be done as part of next PR for more documentation

**Review by ChristianDarr-personal — COMMENTED** [review]
LGTM

**Review by presatish — APPROVED** [review]
